title: "Law, Yao Hua"
description: "Works, thoughts, and ideas of Law, Yao Hua, journalist."
url: "https://yhlreporter.github.io"
baseurl: "/law-yao-hua"

author: "Law, Yao Hua"

# Build settings
markdown: kramdown
permalink: /:categories/:year:month:day/:title/
future: true

plugins:
  - jekyll-sitemap

# Exclude from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
